server:
  port: 8100




#for discovery service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





spring:
  application:
    #display name in Eureka
    name: order
  config:
    import: optional:configserver:http://localhost:8888

  #postgresql connecting
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect




management:
  tracing:
    sampling:
      probability: 1.0